import type { AgeBand, Audience } from "@/lib/schemas";

/**
 * Illustrated backdrops for the visit video (public/video/scenes/*.webp,
 * generated by scripts/gen-scenes.ts). Chosen by age band and who the
 * messages go to; never by race, ethnicity or insurance.
 */
export const BACKDROP_KEYS = ["child", "teen", "young_adult", "adult", "midlife", "older_adult"] as const;
export type BackdropKey = (typeof BACKDROP_KEYS)[number];

export function backdropFor(ageBand: AgeBand, audience: Audience): BackdropKey {
  if (ageBand === "pediatric") return "child";
  if (ageBand === "adolescent") return "teen";
  if (ageBand === "older_adult") return "older_adult";
  if (audience === "caregiver" || audience === "multi_caregiver" || audience === "self_plus_caregiver") return "older_adult";
  if (ageBand === "young_adult") return "young_adult";
  if (ageBand === "midlife") return "midlife";
  return "adult";
}

export function backdropSrc(key: BackdropKey): string {
  return `/video/scenes/${key}.webp`;
}

export const DEFAULT_BACKDROP = backdropSrc("adult");
