import type { Scene, VideoScript } from "@/lib/schemas";

/**
 * Spot illustrations (public/video/spots/*.webp, generated by scripts/gen-scenes.ts):
 * one picture per idea, chosen from the scene's own words so the visual adds
 * meaning instead of repeating the caption. English and Spanish keywords.
 */
export const SPOT_KEYS = [
  "calendar",
  "arrive",
  "front_desk",
  "vitals",
  "heart_scan",
  "blood_test",
  "talk_team",
  "bring_someone",
  "quiet_room",
  "phone_call",
  "medicines",
  "home_rest",
  "questions",
  "family_support",
  "walk_outside",
] as const;
export type SpotKey = (typeof SPOT_KEYS)[number];

/** Most specific first: the first rule that matches wins. */
const RULES: [SpotKey, RegExp][] = [
  ["heart_scan", /\b(echo|ultrasound|scan|imaging|ecocardio|ecograf|ultrasonido)/i],
  ["blood_test", /\b(blood (test|work|draw|sample)|lab(s|oratory)?\b|a1c|análisis|muestra de sangre|laboratorio)/i],
  ["vitals", /\b(blood pressure|pressure|vitals?|weigh|temperature|presión|signos vitales|pesar)/i],
  ["medicines", /\b(medicine|medication|meds|pills?|dose|insulin|inhaler|medicin|pastilla|dosis)/i],
  ["phone_call", /\b(call|text us|phone|555|reach us|llam|escríb|teléfono|mensaje)/i],
  ["bring_someone", /\b(bring|someone with you|partner|companion|traer|acompañ|venir con)/i],
  ["quiet_room", /\b(quiet|calm|break|pause|breath|stop any time|tranquil|pausa|respir|descanso)/i],
  ["questions", /\b(questions?|ask|wonder|pregunt)/i],
  ["front_desk", /\b(check[- ]?in|front desk|register|registr|recepción)/i],
  ["arrive", /\b(arrive|early|entrance|parking|llegue|llegar|temprano|entrada)/i],
  ["calendar", /\b(when|date|day|time|schedule|appointment|monday|tuesday|wednesday|thursday|friday|saturday|sunday|\d{1,2}:\d{2}|cuándo|fecha|día|hora|cita|lunes|martes|miércoles|jueves|viernes|sábado|domingo)/i],
  ["family_support", /\b(family|daughter|son|wife|husband|caregiver|care partner|familia|hija|hijo|esposa|esposo|cuidador)/i],
  ["home_rest", /\b(rest|home|sleep|recover|descans|casa|dormir)/i],
  ["walk_outside", /\b(walk|exercise|active|move|camin|ejercicio|activ)/i],
  ["talk_team", /\b(talk|plan|review|discuss|doctor|team|nurse|together|hablar|plan|equipo|revis|juntos|médic|enfermer)/i],
];

export function spotForText(text: string, avoid: Set<SpotKey> = new Set()): SpotKey {
  for (const [key, re] of RULES) if (re.test(text) && !avoid.has(key)) return key;
  for (const [key, re] of RULES) if (re.test(text)) return key;
  return "talk_team";
}

export function spotSrc(key: SpotKey): string {
  return `/video/spots/${key}.webp`;
}

const CALL = /\b(call|text|phone|555|llam|escrib)/i;

function sceneText(scene: Scene): string {
  return [scene.title ?? "", scene.text, ...(scene.items ?? []), scene.voiceover].join(" ");
}

/**
 * One spot per scene (title scenes use the character backdrop instead), never the
 * same spot twice in a row. Closing scenes prefer the phone call; steps scenes get
 * one spot per item.
 */
export function spotsForScript(script: VideoScript): { scene: SpotKey | null; items: SpotKey[] }[] {
  const out: { scene: SpotKey | null; items: SpotKey[] }[] = [];
  const closingCalls = script.scenes.some((scene) => scene.kind === "closing" && CALL.test(sceneText(scene)));
  let previous: SpotKey | null = null;
  for (const scene of script.scenes) {
    if (scene.kind === "title") {
      out.push({ scene: null, items: [] });
      previous = null;
      continue;
    }
    const avoid: Set<SpotKey> = new Set<SpotKey>(previous ? [previous] : []);
    let key: SpotKey;
    if (scene.kind === "closing") key = CALL.test(sceneText(scene)) ? "phone_call" : spotForText(sceneText(scene), avoid);
    else if (scene.kind === "card" && /\b(when|where|cuándo|dónde)/i.test(scene.title ?? "")) key = "calendar";
    else {
      // The phone call is the sign-off picture: keep it for the closing scene.
      if (closingCalls) avoid.add("phone_call");
      key = spotForText(sceneText(scene), avoid);
      if (avoid.has(key)) key = previous === "talk_team" ? "questions" : "talk_team";
    }
    const used = new Set<SpotKey>();
    const items = (scene.items ?? []).map((item) => {
      const k = spotForText(item, used);
      used.add(k);
      return k;
    });
    out.push({ scene: key, items });
    previous = key;
  }
  return out;
}
