import { BabyIcon, BrainIcon, CpuIcon, DatabaseIcon, HeartHandshakeIcon, LanguagesIcon, SlidersHorizontalIcon, SparklesIcon, StarIcon, UserIcon, UsersIcon, type LucideIcon } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { AUDIENCE_LABEL, type Audience, type ClaimKind, type DemoRole, type RunSource } from "@/lib/schemas";
import { cn } from "@/lib/utils";

const AUDIENCE_ICON: Record<Audience, LucideIcon> = {
  self: UserIcon,
  caregiver: HeartHandshakeIcon,
  care_partner: UsersIcon,
  dual_teen_guardian: UsersIcon,
  dual_child_parent: BabyIcon,
  self_plus_caregiver: UsersIcon,
  multi_caregiver: UsersIcon,
  self_plus_family: UsersIcon,
};

export function AudienceBadge({ audience, className }: { audience: Audience; className?: string }) {
  const Icon = AUDIENCE_ICON[audience];
  return (
    <Badge variant="secondary" className={cn("gap-1 font-normal", className)}>
      <Icon aria-hidden /> {AUDIENCE_LABEL[audience]}
    </Badge>
  );
}

export function DementiaBadge() {
  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <Badge variant="outline" className="gap-1 font-normal text-inferred border-inferred/40">
          <BrainIcon aria-hidden /> Cognitive support
        </Badge>
      </TooltipTrigger>
      <TooltipContent>Dementia, delirium or stroke on the chart: short sentences, caregiver co-addressed.</TooltipContent>
    </Tooltip>
  );
}

export function LanguageBadge({ language }: { language: "en" | "es" }) {
  if (language === "en") return null;
  return (
    <Badge variant="outline" className="gap-1 font-normal">
      <LanguagesIcon aria-hidden /> Spanish (stated)
    </Badge>
  );
}

const DEMO_ROLE_LABEL: Record<NonNullable<DemoRole>, string> = { ideal: "Demo: ideal case", complex: "Demo: complex case", edge: "Demo: edge case" };

export function DemoRoleBadge({ role }: { role: DemoRole }) {
  if (!role) return null;
  return (
    <Badge variant="outline" className="gap-1 font-normal text-teal border-teal/40">
      <StarIcon aria-hidden /> {DEMO_ROLE_LABEL[role]}
    </Badge>
  );
}

const SOURCE: Record<RunSource, { label: string; icon: LucideIcon; className: string; help: string }> = {
  live: { label: "Live model", icon: CpuIcon, className: "text-teal border-teal/40", help: "Generated by Claude for this build, then checked by rules." },
  cached: { label: "Cached output", icon: DatabaseIcon, className: "text-warn border-warn/40", help: "Precomputed model output. Used when the model is unavailable or in the guided demo." },
  fallback: { label: "Rules-based fallback", icon: SlidersHorizontalIcon, className: "text-muted-foreground", help: "Deterministic templates. Plainer than the model, never blank." },
};

export function SourceBadge({ source, className }: { source: RunSource; className?: string }) {
  const s = SOURCE[source];
  const Icon = s.icon;
  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <Badge variant="outline" className={cn("gap-1 font-normal", s.className, className)}>
          <Icon aria-hidden /> {s.label}
        </Badge>
      </TooltipTrigger>
      <TooltipContent>{s.help}</TooltipContent>
    </Tooltip>
  );
}

export const CLAIM_KIND: Record<ClaimKind, { label: string; className: string; icon: LucideIcon; help: string }> = {
  fact: { label: "Fact", className: "bg-teal-soft text-teal border-transparent", icon: DatabaseIcon, help: "Documented in the record. Click to see the source." },
  inferred: { label: "Inferred · confirm", className: "bg-inferred-soft text-inferred border-transparent", icon: SparklesIcon, help: "The model's judgment from cited facts. Confirm before you rely on it." },
  patient_stated: { label: "Patient-stated", className: "bg-stated-soft text-stated border-transparent", icon: UserIcon, help: "From the \"What matters to you\" check-in." },
};

export function ClaimKindBadge({ kind, confirmed, className }: { kind: ClaimKind; confirmed?: boolean; className?: string }) {
  const k = CLAIM_KIND[kind];
  const Icon = k.icon;
  const label = kind === "inferred" && confirmed ? "Inferred · confirmed" : k.label;
  return (
    <Badge className={cn("gap-1 font-normal", k.className, kind === "inferred" && confirmed && "bg-ok-soft text-ok", className)}>
      <Icon aria-hidden /> {label}
    </Badge>
  );
}

/** Score pill: color plus the number plus a word, never color alone. */
export function ScorePill({ score, blocked, size = "md", className }: { score: number; blocked?: boolean; size?: "sm" | "md" | "lg"; className?: string }) {
  const tone = blocked ? "bad" : score >= 85 ? "ok" : score >= 60 ? "warn" : "bad";
  const word = blocked ? "Blocked" : score >= 85 ? "Trauma-informed" : score >= 60 ? "Getting there" : "Generic";
  const toneClass = { ok: "bg-ok-soft text-ok", warn: "bg-warn-soft text-warn", bad: "bg-bad-soft text-bad" }[tone];
  return (
    <span
      className={cn(
        "inline-flex items-baseline gap-1.5 rounded-full font-medium tabular-nums",
        toneClass,
        size === "lg" ? "px-3 py-1 text-base" : size === "sm" ? "px-2 py-0.5 text-xs" : "px-2.5 py-0.5 text-sm",
        className,
      )}
      aria-label={`Trauma-informed score ${score} out of 100, ${word}`}
    >
      <span className={cn("font-semibold", size === "lg" && "text-2xl leading-none")}>{score}</span>
      <span className="opacity-80">/100 · {word}</span>
    </span>
  );
}
